# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20161108_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='departamento',
            field=models.IntegerField(choices=[(1, 'DEL'), (2, 'Mecanica')], default=1),
        ),
        migrations.AddField(
            model_name='recurso',
            name='nome',
            field=models.CharField(default='Nome do recurso...', max_length=250),
        ),
        migrations.AddField(
            model_name='recurso',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponivel'), (2, 'Alocado'), (3, 'Em Manutencao'), (4, 'Desativado')], default=1),
        ),
    ]
