# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20161108_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_inicial',
            field=models.DateTimeField(),
        ),
    ]
