# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_agendamento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='referencia',
            field=models.CharField(default='Identificador unico do recurso', max_length=50, unique=True),
        ),
    ]
